GET_METHOD = "GET"
HEAD_METHOD = "HEAD"
POST_METHOD = "POST"
PUT_METHOD = "PUT"
PATCH_METHOD = "PATCH"
DELETE_METHOD = "DELETE"
OPTIONS_METHOD = "OPTIONS"
TRACE_METHOD = "TRACE"
CONNECT_METHOD = "CONNECT"

ALLOWED_METHODS = [GET_METHOD, HEAD_METHOD, POST_METHOD, PUT_METHOD, PATCH_METHOD, DELETE_METHOD, OPTIONS_METHOD,
                   TRACE_METHOD, CONNECT_METHOD]
SAFE_METHODS = [GET_METHOD, HEAD_METHOD, OPTIONS_METHOD, TRACE_METHOD]
IDEMPOTENT_METHODS = [PUT_METHOD, DELETE_METHOD, GET_METHOD, HEAD_METHOD, OPTIONS_METHOD, TRACE_METHOD]
REQUEST_HAS_BODY_METHODS = [POST_METHOD, PUT_METHOD, CONNECT_METHOD, PATCH_METHOD]
RESPONSE_HAS_BODY_METHODS = [GET_METHOD, POST_METHOD, PUT_METHOD, DELETE_METHOD, CONNECT_METHOD, OPTIONS_METHOD,
                             TRACE_METHOD, PATCH_METHOD]
